[package]
name = "python-rusty-testgen"
version = "0.1.0"
edition = "2021"

[dependencies]
rustpython-ast = { version = "0.4.0", features = ["visitor", "rustpython-literal"] }
rustpython-parser = "0.4.0"
thiserror = "2.0.12"
z3 = "0.12.1"
