name: Rust Code Quality

on: [push, pull_request]

jobs:
  rust-lint-format:
    name: Rust Syntax, Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check for Syntax Errors
        run: cargo check --all-targets --all-features

      - name: Check Formatting
        run: cargo fmt -- --check
